#!/usr/bin/env python3

import sys
import math

def multi_matrice(matrice, matrice_2):
    new_matrice = [[0,0,0], [0,0,0], [0,0,0]]
    for i in range(3):
        for j in range(3):
            for k in range(3):
                new_matrice[i][j] += matrice[i][k] * matrice_2[k][j]
    return new_matrice

def translation(i, j):
    translation = [[1,0,i],[0,1,j],[0,0,1]]
    print("Translation along vector", f"({i:.0f}, {j:.0f})")
    return translation

def scaling(n, m):
    scaling = [[n,0,0],[0,m,0],[0,0,1]]
    print("Scaling by factors", f"{n:.0f}", "and", f"{m:.0f}")
    return scaling

def rotation(d):
    print("Rotation by a", f"{d:.0f}", "degree angle")
    d = d/180 * (math.pi)
    rotation = [[math.cos(d), (math.sin(d) * -1), 0],[math.sin(d), math.cos(d), 0],[0,0,1]]
    return rotation

def reflexion(d):
    temp = d
    d = d/180 * (math.pi)
    reflexion = [[math.cos(2*d), math.sin(2*d), 0],[math.sin(2*d), math.cos(2*d) * -1, 0],[0,0,1]]
    print("Reflection over an axis with an inclination angle of", f"{temp:.0f}", "degrees")
    return reflexion

def main():
    if (len(sys.argv) < 5):
        sys.exit(84)
    for i in range(1, len(sys.argv)):
        if ((sys.argv[i] != '-t' and sys.argv[i] != '-z' and sys.argv[i] != '-r' and sys.argv[i] != '-s') and sys.argv[i].lstrip("-").isdigit() == False):
            sys.exit(84)
    cpt = 3
    reverse_matrice = []
    x = float(sys.argv[1])
    y = float(sys.argv[2])
    matrice = [[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]]
    matrice_final = []
    if len(sys.argv) == 3:
        print(f"({x:.2f}, {y:.2f}, {1:.2f})")
        return 0
    for l in range (3, len(sys.argv)):
        if (sys.argv[l] == '-t'):
            try: 
                if (len(sys.argv) == 5):
                    sys.exit(84)
                i = float(sys.argv[l + 1])
                j = float(sys.argv[l + 2])
                matrice = translation(i, j)
                reverse_matrice.append(matrice)
                x += i
                y += j
                cpt += 3
            except ValueError:
                sys.exit(84)
        if (sys.argv[l] == '-z'):
            try:
                if (len(sys.argv) == 5):
                    sys.exit(84)
                n = float(sys.argv[l + 1])
                m = float(sys.argv[l + 2])
                matrice = scaling(n, m)
                reverse_matrice.append(matrice)
                x *= n
                y *= m
                cpt += 3
            except ValueError:
                sys.exit(84)
        if (sys.argv[l] == '-r'):
            try:
                d = int(sys.argv[l + 1])
                matrice = rotation(d)
                reverse_matrice.append(matrice)
                new_x = x * matrice[0][0] + y * matrice[0][1]
                new_y = x * matrice[1][0] + y * matrice[1][1]
                x = new_x
                y = new_y
                cpt += 2
            except ValueError:
                sys.exit(84)
        if (sys.argv[l] == '-s'):
            try:
                d = int(sys.argv[l + 1])
                matrice = reflexion(d)
                reverse_matrice.append(matrice)
                if (len(sys.argv) == 5 and matrice[1][1] < 0.00):
                    matrice[1][1] = 0.00
                new_x = x * matrice[0][0] + y * matrice[0][1]
                new_y = x * matrice[1][0] + y * matrice[1][1]
                x = new_x
                y = new_y
                cpt += 2
            except ValueError:
                sys.exit(84)
    if (cpt != len(sys.argv)):
        sys.exit(84)
    matrice_final = reverse_matrice[-1]
    for i in range(len(reverse_matrice) - 2, -1, -1):
        matrice_final = multi_matrice(matrice_final, reverse_matrice[i])
    for i in range(3):
         print("%.2f\t"%matrice_final[i][0] + "%.2f\t"%matrice_final[i][1] + "%.2f"%matrice_final[i][2])
    print(f"({float(sys.argv[1]):.2f}, {float(sys.argv[2]):.2f}) => ({x:.2f}, {y:.2f})")
    return 0
main()
